spring:
  application:
    name: coupon
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/coupon
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false


  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  data:
    redis:
      port: 6379
      host: localhost


logging:
  level:
    org.hibernate.SQL: debug


coupon:
  topic: coupon.requested